// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxyxBxzn5ehH184TVn07oqGvZMxauwoAQ',
    appId: '1:670765490205:web:77a5b4e61e8ec4b774a6f4',
    messagingSenderId: '670765490205',
    projectId: 'puzzles-701a8',
    authDomain: 'puzzles-701a8.firebaseapp.com',
    storageBucket: 'puzzles-701a8.appspot.com',
    measurementId: 'G-PSE08RXN7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnX4BD_IEJlYQuEjC9DjfUq1tDc8eeYs',
    appId: '1:670765490205:android:63589292a05f9aab74a6f4',
    messagingSenderId: '670765490205',
    projectId: 'puzzles-701a8',
    storageBucket: 'puzzles-701a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBVVa2BlsnfRkZmw3WmV_OGZs3etFeOS8',
    appId: '1:670765490205:ios:6338684d739eb31374a6f4',
    messagingSenderId: '670765490205',
    projectId: 'puzzles-701a8',
    storageBucket: 'puzzles-701a8.appspot.com',
    iosBundleId: 'com.example.sellers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBVVa2BlsnfRkZmw3WmV_OGZs3etFeOS8',
    appId: '1:670765490205:ios:6338684d739eb31374a6f4',
    messagingSenderId: '670765490205',
    projectId: 'puzzles-701a8',
    storageBucket: 'puzzles-701a8.appspot.com',
    iosBundleId: 'com.example.sellers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxyxBxzn5ehH184TVn07oqGvZMxauwoAQ',
    appId: '1:670765490205:web:67cc7fb7333b068174a6f4',
    messagingSenderId: '670765490205',
    projectId: 'puzzles-701a8',
    authDomain: 'puzzles-701a8.firebaseapp.com',
    storageBucket: 'puzzles-701a8.appspot.com',
    measurementId: 'G-9417QPRJ67',
  );
}
